### ISSUE TITLE
Make the link to the games section more obvious

### ISSUE THREAD

**Issue by nazarkvartalnyi** [Inoxoft/TranslateTribune-Mobile#5]
From TranslateTribune-Mobile created by [predbrad](https://github.com/predbrad): Inoxoft-Company/TranslateTribune-Mobile#1  

It is really hard to find the games section from the hamburger menu and might be better if we have a more prominent link on the app homepage to the games. Please consider it! Thanks.

**Comment by ruslanpitula** [comment]
Updated UI with TabBar controller in the bottom of app. So games are accessible much easier now. 
<img width="395" alt="image" src="https://github.com/Inoxoft/TranslateTribune-Mobile/assets/91199564/60b94262-ae8a-41e7-81c7-c7d5b64d6f1e">
